# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZOOfAoRAMwgXChI+18r+db01Il0nHJqbBUthxF+GNFz4LxM6POVW8kKT31sP++aG8O1tE3R5ioLGV2YFY1JyneepPRzSEen46AkPPYdn5y25sLx0KnaV1dHi+g+uzhI1hQ0pB9aoGlbdz0T/1cpFrxKYqaR4kWiVjBKoM4DABTN02WBNB5QPomu5TxR5sItGp61zueE/F69VEe2Mio5Ol8W/0cpQjyYSnzQFZcJIoLJeqmKTRYhtcQqaUUoHT+lj1ftxHOzsiUZDIUYIL1kGOa7JS4XDsF4JJmZfnOXw8HJRR02d8mqNwZW3TXljSzuq32HfmW5CO9XYVNLCCGE9IrwJCMeos3NMx1xzBb7ly7111uh/09K/ygQDuF1DgM6q0pq+F/iE78XUjtfheK147qYQ+PTxrsC9KWD92tyirAUzt57lrtZgGZq2vZe3A/gNdhVENrhfW1S+4p5B8s/73wy8mPlWfA4WfDr7n9vppLHbY8/RnqD2HTdKQa3zsRkLnWFqtmBDrDi4DCh8FlL6MTXiSw+qxZeOWC5eia4rbnsy2k4nJzz51CLV53wPORd/soHfbcep86OQZq/lFCS8dAG2Ip4eyyd1Rpun3/RTVAg25CLqzRMTjTUz+jUTRCN9W6XaTBXOCrT85PuI7aNTecnd9o1Ecd/uVKIbQFeyCPs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
