# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JF+iiVjMkWjvjEU9xMHQg44rOHR/3Qlb00e1pUO5Kyq8dXoOKeYsq+QRP2OxMDukkcbVjbBWQ5ercE59oZU/svgqDup6HgPZNPoCu+ywwg4ET8rR+ffCWzdrYb5V80jsLQs+LXjDBSQ5LjyuAROdwV1E99nwQA/VxGOu1sCJUZRz60C0oqSuXERYh250OgbHQ9SUZVxYtulKTrnEI6mh4LgyjGrpjaCfmhyYLIrvj8sPraQGa9K2XypmIkrtU27EjJ8R95uq4EBDGrn9hpolAPN13LlEAAfoPN/41NsUV86UNSjXALwIxxbGZx0H8fbUjpDsFG4TAtiJtLdHRwrsCP+DKGlf0zcIdKVF+qQXsBGunFc35dRjyXOdnR94t0RYq1UdaGmcXfmb/VGexmNsTiu0p+l2MLtHmXbyxjNZvoGaP9ph7Jgic23sKq4wiM3EiQ9dIhdiOg1m5BYZlVLga2r44Q1pKikfi5DcgAAeKcQ0tK7QqUks/x6r6GnjHl84HQLqeR3xCRvElYyPoWFcAjWRV/RQRj5jSSZC5iByceBDB6tESEJuiGWkN/GQiN53n8q3L69zVHNB10S3hdK9bm1Mc2jogScndPuVgFc4LsPFMLSZnboUZsHfuXjcl1PJZn3gv/JmBgo3UFbFRgkdM5P5gxVVx2SysWe37VFE5Q4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
