travis:
  secure:
    BINSTAR_TOKEN: ZOOfAoRAMwgXChI+18r+db01Il0nHJqbBUthxF+GNFz4LxM6POVW8kKT31sP++aG8O1tE3R5ioLGV2YFY1JyneepPRzSEen46AkPPYdn5y25sLx0KnaV1dHi+g+uzhI1hQ0pB9aoGlbdz0T/1cpFrxKYqaR4kWiVjBKoM4DABTN02WBNB5QPomu5TxR5sItGp61zueE/F69VEe2Mio5Ol8W/0cpQjyYSnzQFZcJIoLJeqmKTRYhtcQqaUUoHT+lj1ftxHOzsiUZDIUYIL1kGOa7JS4XDsF4JJmZfnOXw8HJRR02d8mqNwZW3TXljSzuq32HfmW5CO9XYVNLCCGE9IrwJCMeos3NMx1xzBb7ly7111uh/09K/ygQDuF1DgM6q0pq+F/iE78XUjtfheK147qYQ+PTxrsC9KWD92tyirAUzt57lrtZgGZq2vZe3A/gNdhVENrhfW1S+4p5B8s/73wy8mPlWfA4WfDr7n9vppLHbY8/RnqD2HTdKQa3zsRkLnWFqtmBDrDi4DCh8FlL6MTXiSw+qxZeOWC5eia4rbnsy2k4nJzz51CLV53wPORd/soHfbcep86OQZq/lFCS8dAG2Ip4eyyd1Rpun3/RTVAg25CLqzRMTjTUz+jUTRCN9W6XaTBXOCrT85PuI7aNTecnd9o1Ecd/uVKIbQFeyCPs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
