appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: JF+iiVjMkWjvjEU9xMHQg44rOHR/3Qlb00e1pUO5Kyq8dXoOKeYsq+QRP2OxMDukkcbVjbBWQ5ercE59oZU/svgqDup6HgPZNPoCu+ywwg4ET8rR+ffCWzdrYb5V80jsLQs+LXjDBSQ5LjyuAROdwV1E99nwQA/VxGOu1sCJUZRz60C0oqSuXERYh250OgbHQ9SUZVxYtulKTrnEI6mh4LgyjGrpjaCfmhyYLIrvj8sPraQGa9K2XypmIkrtU27EjJ8R95uq4EBDGrn9hpolAPN13LlEAAfoPN/41NsUV86UNSjXALwIxxbGZx0H8fbUjpDsFG4TAtiJtLdHRwrsCP+DKGlf0zcIdKVF+qQXsBGunFc35dRjyXOdnR94t0RYq1UdaGmcXfmb/VGexmNsTiu0p+l2MLtHmXbyxjNZvoGaP9ph7Jgic23sKq4wiM3EiQ9dIhdiOg1m5BYZlVLga2r44Q1pKikfi5DcgAAeKcQ0tK7QqUks/x6r6GnjHl84HQLqeR3xCRvElYyPoWFcAjWRV/RQRj5jSSZC5iByceBDB6tESEJuiGWkN/GQiN53n8q3L69zVHNB10S3hdK9bm1Mc2jogScndPuVgFc4LsPFMLSZnboUZsHfuXjcl1PJZn3gv/JmBgo3UFbFRgkdM5P5gxVVx2SysWe37VFE5Q4=}
conda_forge_output_validation: true
